# Generated by Django 4.1.13 on 2025-05-23 01:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0002_assignmentresponse_best_practices_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignmentresponse',
            name='best_practices',
        ),
        migrations.RemoveField(
            model_name='assignmentresponse',
            name='failed_test_cases',
        ),
        migrations.RemoveField(
            model_name='assignmentresponse',
            name='feedback',
        ),
        migrations.RemoveField(
            model_name='assignmentresponse',
            name='issues',
        ),
        migrations.RemoveField(
            model_name='assignmentresponse',
            name='key_concepts',
        ),
        migrations.RemoveField(
            model_name='assignmentresponse',
            name='suggestions',
        ),
    ]
