# Generated by Django 4.1.13 on 2025-05-23 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0003_remove_assignmentresponse_best_practices_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmentresponse',
            name='feedback',
            field=models.TextField(blank=True, default=''),
        ),
    ]
