# Generated by Django 4.1.13 on 2026-01-01 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0004_assignmentresponse_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizquestionresponse',
            name='code_quality_score',
            field=models.FloatField(blank=True, help_text='Code quality score (0-1)', null=True),
        ),
        migrations.AddField(
            model_name='quizquestionresponse',
            name='code_similarity',
            field=models.FloatField(blank=True, help_text='Code similarity for coding questions (0-1)', null=True),
        ),
        migrations.AddField(
            model_name='quizquestionresponse',
            name='score',
            field=models.FloatField(blank=True, default=0.0, help_text='Numeric score (0-100)', null=True),
        ),
        migrations.AddField(
            model_name='quizquestionresponse',
            name='semantic_similarity',
            field=models.FloatField(blank=True, help_text='Semantic similarity for theory questions (0-1)', null=True),
        ),
        migrations.AddField(
            model_name='quizquestionresponse',
            name='test_pass_rate',
            field=models.FloatField(blank=True, help_text='Test case pass rate for coding questions (0-1)', null=True),
        ),
    ]
